insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("TEC","SUBJECT1","hello.. ! mynames David...!","David","2016-12-03 18:22:31");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("Com","Herry UP!!!","herry up yours working plz!!!!","ji hoon","2016-12-06 09:22:15");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("TEC","개발요청건","이것을 만들어 주세요.","ji hoon","2016-12-08 15:00:11");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("경영","디자인수정","디자인 수정사항입니다. 첨부파일 참조","김천일","2016-12-11 13:27:14");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("TEC","SUBJECT1","hello.. ! mynames David...!","David","2016-12-03 18:22:31");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("Com","Herry UP!!!","herry up yours working plz!!!!","ji hoon","2016-12-06 09:22:15");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("TEC","개발요청건","이것을 만들어 주세요.","ji hoon","2016-12-08 15:00:11");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("경영","디자인수정","디자인 수정사항입니다. 첨부파일 참조","김천일","2016-12-11 13:27:14");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("TEC","SUBJECT1","hello.. ! mynames David...!","David","2016-12-03 18:22:31");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("Com","Herry UP!!!","herry up yours working plz!!!!","ji hoon","2016-12-06 09:22:15");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("TEC","개발요청건","이것을 만들어 주세요.","ji hoon","2016-12-08 15:00:11");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("경영","디자인수정","디자인 수정사항입니다. 첨부파일 참조","김천일","2016-12-11 13:27:14");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("TEC","SUBJECT1","hello.. ! mynames David...!","David","2016-12-03 18:22:31");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("Com","Herry UP!!!","herry up yours working plz!!!!","ji hoon","2016-12-06 09:22:15");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("TEC","개발요청건","이것을 만들어 주세요.","ji hoon","2016-12-08 15:00:11");
insert into SN_NOTICE (cate,title,contents,writer,regist_day) values ("경영","디자인수정","디자인 수정사항입니다. 첨부파일 참조","김천일","2016-12-11 13:27:14");